### PR TITLE
Allow to use inner classes in btree files

### LINKED ISSUE #101: Use inner class in btree file
#### Issue details
It's not possible to use inner classes in btree file (parser does not allow '$' character used for separating class names).

#### Reproduction steps/code
1. Create a public static inner class.
2. Use full name instead of import in btree file.
3. `com.badlogic.gdx.utils.SerializationException`: Error parsing behavior tree on line 3 near: $Inner

OuterClass.java:
```
package test;

import com.badlogic.gdx.ai.btree.leaf.Success;

public class OuterClass {
	public static class Inner<E> extends Success<E> {}
}
```

mytree.btree:
```
root
	selector
		test.OuterClass$Inner
```

#### Version of gdx-ai and/or relevant dependencies
1.8.1

#### Stacktrace
```
com.badlogic.gdx.utils.SerializationException: Error parsing behavior tree on line 3 near: $Inner
	at com.badlogic.gdx.ai.btree.utils.BehaviorTreeReader.parse(BehaviorTreeReader.java:541)
	at com.badlogic.gdx.ai.btree.utils.BehaviorTreeParser$DefaultBehaviorTreeReader.parse(BehaviorTreeParser.java:326)
	at com.badlogic.gdx.ai.btree.utils.BehaviorTreeReader.parse(BehaviorTreeReader.java:92)
	at com.badlogic.gdx.ai.btree.utils.BehaviorTreeReader.parse(BehaviorTreeReader.java:118)
```

### PR DESCRIPTION
**Pull request by Genhis**
Fixes #101

### CODE REVIEW

**Comment by davebaol** [comment]
The `$` should be legal only after the last '.'
I mean, if I got it right your change allows illegal stuff like `package.Class$Inner.package2`.
Correct me if I'm wrong.

**Comment by Genhis** [comment]
You are correct; however, I couldn't find a way to do it, and since the issue has been open for more than a year, I wanted to contribute with my (though not optimal) solution.

I do not know Ragel, so I just edited the file manually in the simplest way I could and let ragel to build the java file. I would appreciate any advice regarding Ragel.

If you know how to quickly fix it, feel free to close this pull request.

**Comment by davebaol** [comment]
Please, try the following
```
id = [a-zA-Z_] [a-zA-Z_0-9]*;
...
taskName = idBegin ('.' id)* ('$' id)* '?'? %{isSubtreeRef = false;} %taskName;
```
This change should cover the following sample task names:
- default package
  - Class 
  - Class$Inner
  - Class$Inner$Inner2$Inner3$...
- non default package
  - a.b.c.Class
  - a.b.c.Class$Inner
  - a.b.c.Class$Inner$Inner2$...

Please, let me know if it works as expected.

**Comment by Genhis** [comment]
It works as expected, thanks :)
I updated the PR to reflect your changes.

**Comment by davebaol** [comment]
Merged! Thanks :)

**Pull request merged**
