### PR TITLE
Added toParsableString in Distribution

### PR DESCRIPTION
**Pull request by piotr-j**
Added ```toParsableString``` in various ```Distribution```s to facilitate generation of parseable trees from in memory ```BehaviourTree```

### CODE REVIEW

**Comment by davebaol** [comment]
I guess you need this to generate the tree file from your editor, right?

**Comment by piotr-j** [comment]
Yep, I can do without it, but it would be cleaner like that.

2015-10-21 1:35 GMT+02:00 davebaol <notifications@github.com>:

**Comment by davebaol** [comment]
TBH I've mixed feelings about this.
On the one hand I see why you want it and I recognize it can be cleaner, on the other hand distributions are general purpose classes that have nothing to do with behavior trees and their syntax.
However, `XXXDistribution` classes already have a static parse method that creates instances of subclasses. :scream: 
I'd really like a better design. Any ideas?

**Comment by piotr-j** [comment]
I agree, its not the best as is. But i don't really see how to do this in much better way. Perhaps separate class for parsing/stringing. It sure would be nice if we could have generic primitives.

**Comment by piotr-j** [comment]
Looks good to me!

**Pull request closed without merging**
