### PR TITLE
Ability to remove steering behaviors from BlendedSteering

### PR DESCRIPTION
**Pull request by lukz**
Hi! I need ability to remove steering behaviors from BlendedSteering so here's PR.

Case:
I want to combine steering behaviors using behavior trees. Idea is to have steering behaviors leafs running inside parallel composite and add / remove them from blended steering in start() / end() methods of behavior leafs.

### CODE REVIEW

**Comment by davebaol** [comment]
I've not looked at your code since I'm on the smartphone right now. But why cannot you just enable/disable steering behaviors?

**Comment by lukz** [comment]
I'm not sure how that would work. Seems pretty complicated.

This will require to add all possible steering behavior variations at the begging of the tree (in my example I'm using Arrive twice in tree with different attributes) to BlendedSteering (one leaf each). And than inside tree I need another leafs to enable / disable those behaviors. Another problem is that I have to somehow uniquely identify each steering behavior (as said before I have ArriveTo twice with different params) to enable / disable them.

Seems pretty complicated.

My current sample:
`# Chicken tree
import log:"com.infunity.game.ai.btree.utils.LogTask"

import isPlayerVisible?:"com.infunity.game.ai.btree.IsPlayerVisible"

import findEmptyPos:"com.infunity.game.ai.btree.movement.EmptyPosInRadiusTask"
import arriveTo:"com.infunity.game.ai.btree.movement.ArriveToTask"
import updatePos:"com.infunity.game.ai.btree.movement.SetPosFromEntityTask"

subtree name:"wanderAround"
  sequence
    wait seconds:"uniform, 2, 5"
    findEmptyPos outVar:"targetPos"
    arriveTo srcVar:"targetPos" timeToTarget: 1

subtree name:"goToPlayer"
  parallel policy:"sequence"
    updatePos entityVar:"targetPlayer" outVar:"targetPlayerPos"
    arriveTo srcVar:"targetPlayerPos" decelerationRadius:0

root
  dynamicGuardSelector
    (isPlayerVisible? range: 192 entityVar:"targetPlayer")  $goToPlayer
    ()                                                      $wanderAround`

**Comment by davebaol** [comment]
I think that it could be done the same way you did it with add/remove. Just make sure to add a behavior only the very first time `start` is executed otherwise simply enable the behavior. In `end` method always disable it.
Does not  sound too hard IMO.
However, since your PR is very simple, I'm open to merge it if you really need it.

**Comment by lukz** [comment]
Your idea seems to work great! So I don't need it currently. I still have to somehow integrate grup behaviors and formations but maybe those will work with same idea.

Thanks!

**Comment by davebaol** [comment]
Glad you got it working.

**Comment by davebaol** [comment]
Thanks

**Pull request merged**
