### PR TITLE
Add "shortCircuit" task attribute to Parallel task

### PR DESCRIPTION
**Pull request by ttilby**
This will allow the Parallel task to fail when one child fails. If a child fails, the Parallel task will call `end()` on all running children and prevent starting any remaining children.

I mimicked the original Dog test, but instead of Rest, I created Play. The main difference is that Play is not checking for any conditions itself, this is instead handled by the Parallel task.

### CODE REVIEW

**Comment by davebaol** [comment]
TBH I'm hesitant to merge this as it is right now.
I think that just calling `end()` to terminate children is not enough. Task termination should go down the hierarchy and terminate nested children I guess.
For example, with your implementation, `SemaphoreGuard` is properly terminated (i.e. the semaphore is released) only if it is a direct child of `Parallel`.

**Comment by ttilby** [comment]
@davebaol 
Thanks for taking the time to look at this and provide feedback.
I added `end()` to `BranchTask` that will loop through all the children to terminate them. Parallel is the only one that overrides this call since it needs to set `runningTasks` to false.
Does this sound like the right approach to you? I will work on writing up some tests to confirm this functionality before I do another pull request but would like to hear your input.

**Comment by davebaol** [comment]
I'll look into it asap. Rather busy right now :/

**Comment by piotr-j** [comment]
Perhaps a notion of ```cancel()``` or something would be useful to distinguish it from regular ```end()```?

**Comment by davebaol** [comment]
Yeah I think so.
I'm going to release gdx-ai 1.6.0 in the week end then l'll look into this.

**Comment by davebaol** [comment]
Closing this. Sorry, I got inspired. :)
I'm currently reviewing the entire API and parallel is one of the things I'm working on. 
I'm going to push changes soon.

**Comment by piotr-j** [comment]
Sounds awesome!

**Comment by davebaol** [comment]
Done, see https://github.com/libgdx/gdx-ai/issues/12#issuecomment-145060773

**Pull request closed without merging**
