### PR TITLE
allow the option to use an external pool in MessageDispatcher

### PR DESCRIPTION
**Pull request by damcaoson**
Hi, as the title suggests, it would be helpful if the `MessageDispatcher` could take an external pool as a parameter, instead of always using the static pool. This is especially useful in parallel messaging situations, as I mentioned in #120.

### CODE REVIEW

**Comment by damcaoson** [comment]
I don't prefer the uppercase `POOL` either. I left it unchanged because I didn't want to alter the git annotation for such a small change. But since you don't like it, I'll update it to lowercase.

**Comment by davebaol** [comment]
@damcaoson Thanks

@Tom-Ski or any other maintainer. I cannot remember where the build server is. So please, send me this info or merge this PR yourself if the remote build succeeds. Thanks 😄

**Comment by Tom-Ski** [comment]
@davebaol think we will migrate this to GHA, because we are doing that everywhere else.

**Comment by davebaol** [comment]
@Tom-Ski Great, thanks.

**Comment by hw207165** [comment]
Any release plan for this MR ?

**Pull request merged**
