### PR TITLE
Handle NaN case when relative velocity is 0

### PR DESCRIPTION
**Pull request by domokato**

### CODE REVIEW

**Comment by domokato** [comment]
From these two lines:

    float relativeSpeed2 = relativeVelocity.len2();
    float timeToCollision = -relativePosition.dot(relativeVelocity) / relativeSpeed2;

0/0 = NaN

**Comment by davebaol** [comment]
If I got it right this can only happen when both relative position and relative velocity are 0, i.e. when the two agents have the same position and velocity.
If so, shouldn't we return `true` ?

**Comment by domokato** [comment]
Anything dot (0,0) will evaluate to 0, so it doesn't matter what relative position is

**Comment by davebaol** [comment]
Well, this behavior is collision __avoidance__, meaning that its target is to prevent collisions by reacting to collision course not to ongoing collisions.
Also when you use a physics engine rigid bodies won't overlap, so the issue does not arise.
As things stand, I think that your solution is more than acceptable.
I've just replaced the `isNaN()` invocation with the faster check `relativeSpeed2 == 0` which is logically equivalent in this particular situation.

**Pull request closed without merging**
